version: 2
jobs:
  build:
    working_directory: ~/docker-rest-api
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: java102-repl-{{ checksum "pom.xml" }}
      - run: ./mvnw clean package
      - save_cache:
          paths:
            - ~/.m2
          key: java102-repl-{{ checksum "pom.xml" }}
      - store_test_results:
          path: target/surefire-reports
      